<!DOCTYPE html> 
<html lang="en"> 
<head>
	<title><?php echo $meta['title']; ?></title>
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $basepath; ?>assets/default.css">
    <!--[if lt IE 7]>
    <style media="screen" type="text/css">
    .col1 {
	    width:100%;
	}
    </style>
    <![endif]-->
	<link rel="stylesheet" type="text/css" href="<?php echo $basepath; ?>assets/code.css">
	<script src="<?php echo $basepath; ?>assets/highlight.js"></script>
	<script>
  	hljs.tabReplace = '    ';
  	hljs.initHighlightingOnLoad();
  	</script>
</head> 
<body> 
<div class="header"> 
	<p>Default</p>
</div> 
<div class="content-wrap">
    <div class="content"> 
        <div class="col-page"> 
            <div class="page">	
				<?php echo $content; ?>
            </div> 
        </div> 
        <div class="menu">
			<?php require('menu.tpl.php'); ?>
        </div> 
    </div> 
</div> 
<div class="footer"> 
	<p>Generated by <a href="http://yarrowdoc.org/">Yarrow</a>.</p>
</div> 
 
</body> 
</html>