<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
  <head>
    <title><?php echo $meta['title']; ?></title>
  </head>
  <body>
	<?php echo $content; ?>
	
	<div class="footer">
		<p>Generated by Yarrow.</p>
	</div>
  </body>
</html>